spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false

http:
  client:
    ssl:
      trust-store: classpath:trustStore
      trust-store-password: tomtom

services:
  iata-codes:
    url: https://iatacodes.org/api/v6/airports
    api-key: a485a7c4-a843-49b8-b3ca-fb73701d6de3
  flight-offer:
    url: https://test.api.amadeus.com/v1
    apiKey: JPavUqYALWrdawC0EGa6GGoqEmSTT4mZ
    apiSecret: J841PHLiXGS1tRTV

